# -*- coding: utf-8 -*-
"""1_Simple_Linear_Regression

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oDtP_Yuby-MZ7mg1isU5UQObfJUJX5aX

# 01. Import Libraries and Data
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

#  from google.colab import drive
#  drive.mount('/content/gdrive')

dataset = pd.read_csv('Salary_Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

dataset.head()

"""# 02. Data Splitting"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)
# dimensi data hanya 1: YearsExperience, Salary yang mau di predict

"""# 03. Training Model"""

regressor = LinearRegression()
regressor.fit(X_train, y_train)

"""# 04. Predicting the Test Data"""

y_pred = regressor.predict(X_test)

"""# 05. Model Evaluation

## 5.1. Visualising the Training set results
"""

plt.scatter(X_train, y_train, color = 'red')
plt.plot(X_train, regressor.predict(X_train), color = 'blue')
plt.title('Salary vs Experience (Training set)')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()

"""## 5.2. Visualising the Test set results"""

plt.scatter(X_test, y_test, color = 'red')
plt.plot(X_train, regressor.predict(X_train), color = 'blue')
plt.title('Salary vs Experience (Test set)')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()