# -*- coding: utf-8 -*-
"""4_Support_Vector_Regression

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YNq56dOpJ6XWRH4vyU_Xq1WAfUg4hVTY

# 01. Import Libraries and Data
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.preprocessing import StandardScaler

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.preprocessing import PolynomialFeatures

#  from google.colab import drive
#  drive.mount('/content/gdrive')

dataset = pd.read_csv('Position_Salaries.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

dataset.head()

"""# 02. Feature Scaling"""

y = y.reshape(len(y),1)

sc_X = StandardScaler()
sc_y = StandardScaler()
X = sc_X.fit_transform(X)
y = sc_y.fit_transform(y)

"""# 03. Data Splitting"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

"""# 04. Training Model"""

regressor = SVR(C = 1,kernel = 'rbf')
regressor.fit(X_train, y_train)

"""# 05. Predicting the Test Data"""

sc_y.inverse_transform([regressor.predict(X_test)])

sc_y.inverse_transform([regressor.predict(sc_X.transform([[6.5]]))])

"""# 06. Model Evaluation"""

regressor.score(X_train,y_train)